### ISSUE TITLE
Ask @msmichellegar how she made proseccoJS' inaugural meetup such a success!

### ISSUE THREAD

**Issue by iteles** [iteles/Ultimate-guide-to-successful-meetups#1]
@msmichellegar & @wallcrawler, we need to have a chat when I'm back in town if you're up for coffee :wink: 

https://twitter.com/msmichellegar/status/634130007976214528

**Comment by msmichellegar** [comment]
Yes! + @nofootnotes. Of course I'm up for coffee :)

**Comment by ronanyeah** [comment]
I think the key is free booze!
